image: Visual Studio 2022
version: 1.0.{build}

build_script:
  - dotnet restore -v quiet
  - ps: dotnet build /p:configuration=Release /p:Version=$($env:appveyor_build_version)

test: off

artifacts:
  - path: HtmlToAmpConverter\**\bin\release\*.nupkg
    name: NuGet package
